/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/predict': typeof PredictRoute
  '/teams': typeof TeamsRoute
  '/tournament': typeof TournamentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/predict': typeof PredictRoute
  '/teams': typeof TeamsRoute
  '/tournament': typeof TournamentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/predict': typeof PredictRoute
  '/teams': typeof TeamsRoute
  '/tournament': typeof TournamentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics' | '/predict' | '/teams' | '/tournament'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/predict' | '/teams' | '/tournament'
  id: '__root__' | '/' | '/analytics' | '/predict' | '/teams' | '/tournament'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  PredictRoute: typeof PredictRoute
  TeamsRoute: typeof TeamsRoute
  TournamentRoute: typeof TournamentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  PredictRoute: PredictRoute,
  TeamsRoute: TeamsRoute,
  TournamentRoute: TournamentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
